# Generated by Django 5.1.2 on 2024-10-21 17:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('question', models.TextField(max_length=500)),
                ('answer', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('country_image', models.ImageField(blank=True, upload_to='photos/countries')),
                ('faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.faq')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=255)),
                ('service_image', models.ImageField(upload_to='photos/services')),
                ('title2', models.CharField(max_length=50, unique=True)),
                ('description2', models.TextField(max_length=255)),
                ('highlight1', models.TextField(max_length=100)),
                ('highlight2', models.TextField(max_length=100)),
                ('highlight3', models.TextField(max_length=100)),
                ('highlight4', models.TextField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.faq')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('age_limit', models.CharField(blank=True, max_length=50, unique=True)),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 21, 22, 49, 16, 10185))),
                ('last_date', models.DateTimeField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.country')),
            ],
        ),
    ]
