# Generated by Django 5.1.2 on 2024-10-21 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'vacancy',
                'verbose_name_plural': 'vacancies',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('profile_image', models.ImageField(upload_to='photos/testimonials')),
                ('video_url', models.URLField()),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
            },
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Faq', 'verbose_name_plural': 'Faq(s)'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'vacancy', 'verbose_name_plural': 'vacancies'},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='description',
            new_name='area',
        ),
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='climate',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='cultural_heritage',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='government',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='major_industries',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='membership',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='natural_features',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='regions',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 22, 0, 2, 1, 435320)),
        ),
    ]
