# Generated by Django 5.1.2 on 2024-10-24 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contact_testimonial_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='area',
            new_name='country_description',
        ),
        migrations.RemoveField(
            model_name='country',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='country',
            name='climate',
        ),
        migrations.RemoveField(
            model_name='country',
            name='cultural_heritage',
        ),
        migrations.RemoveField(
            model_name='country',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='country',
            name='government',
        ),
        migrations.RemoveField(
            model_name='country',
            name='language',
        ),
        migrations.RemoveField(
            model_name='country',
            name='major_industries',
        ),
        migrations.RemoveField(
            model_name='country',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='country',
            name='natural_features',
        ),
        migrations.RemoveField(
            model_name='country',
            name='population',
        ),
        migrations.RemoveField(
            model_name='country',
            name='regions',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 24, 21, 5, 17, 546941)),
        ),
    ]
