# Generated by Django 5.1.2 on 2024-10-24 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_description',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 24, 22, 18, 28, 642374)),
        ),
    ]
