# Generated by Django 5.1.2 on 2024-10-24 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_country_country_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='service',
            name='description2',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='service',
            name='highlight1',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='service',
            name='highlight2',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='service',
            name='highlight3',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='service',
            name='highlight4',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 24, 23, 55, 57, 376498)),
        ),
    ]
